### ISSUE TITLE
Cannot find module 'ember-try-config'

### ISSUE THREAD

**Issue by nbrookie** [sir-dunxalot/ember-google-charts#22] opened 2016-06-20 03:47 UTC
Hey there,

I tried to install `ember-google-charts` in a fresh ember app, and ran into a dependency issue with the `ember-try-config` package:

```
$ ember install ember-google-charts                          
Cannot find module 'ember-try-config'
Error: Cannot find module 'ember-try-config'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/me/dev/frontend/node_modules/ember-cli/node_modules/ember-try/lib/utils/config.js:7:34)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

I was able to install `ember-google-charts` by doing the following:
```
$ npm install ember-try-config
(...snip...)
$ ember install ember-google-charts
```

My current setup is:
- ember-cli 2.6.1
- npm 5.4.1

Anyways, not too big of a deal, and not sure if you guys know about this, but hopefully its saves someone else a few minutes. 🍻

**Comment by sir-dunxalot** [comment] 2016-06-22 18:44
Hi Nick,

Interesting issue. I'm not sure exactly what the cause of the issue is. Perhaps `ember-try-config` needs to be a dev dependency? Have you come across this before?

**Comment by nbrookie** [comment] 2016-06-22 20:05
Hey Duncan, 

I have never ran into this before. I opened an issue with `ember-try` (https://github.com/ember-cli/ember-try/issues/77). Maybe its an issue on their end?

**Comment by sir-dunxalot** [comment] 2016-06-23 21:55
Ok, let's see what the responses are to those two issues and, if need be, we can try updating this addon's dependencies.

**Comment by nathanhammond** [comment] 2016-07-01 05:13
Likely not an issue relevant to this addon. I'd suggest closing it here.

**Comment by nathanhammond** [comment] 2016-07-01 05:14
But! Do update your dependencies here!

**Comment by sir-dunxalot** [comment] 2016-07-04 05:24
Ok, sounds good. Thanks for the follow up and will do!

**Closed by sir-dunxalot** 2016-07-04 05:24 UTC
